'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    
    const classes = [
      {
        name: "F1AM",
        abbreviation: "F1AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F1AV",
        abbreviation: "F1AV",
        shift: "Vespertino",
        year: 2020,
        grade_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F2AM",
        abbreviation: "F2AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F2AV",
        abbreviation: "F2AV",
        shift: "Vespertino",
        year: 2020,
        grade_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F3AM",
        abbreviation: "F3AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F3AV",
        abbreviation: "F3AV",
        shift: "Vespertino",
        year: 2020,
        grade_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F4AM",
        abbreviation: "F4AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F4AV",
        abbreviation: "F4AV",
        shift: "Vespertino",
        year: 2020,
        grade_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F5AM",
        abbreviation: "F5AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F5AV",
        abbreviation: "F5AV",
        shift: "Vespertino",
        year: 2020,
        grade_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F6AM",
        abbreviation: "F6AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F6AV",
        abbreviation: "F6AV",
        shift: "Vespertino",
        year: 2020,
        grade_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F7AM",
        abbreviation: "F7AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F7AV",
        abbreviation: "F7AV",
        shift: "Vespertino",
        year: 2020,
        grade_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F8AM",
        abbreviation: "F8AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F8AV",
        abbreviation: "F8AV",
        shift: "Vespertino",
        year: 2020,
        grade_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F9AM",
        abbreviation: "F9AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "F9AM",
        abbreviation: "F9AM",
        shift: "Vespertino",
        year: 2020,
        grade_id: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "M1AM",
        abbreviation: "M1AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "M2AM",
        abbreviation: "M2AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "M3AM",
        abbreviation: "M3AM",
        shift: "Matutino",
        year: 2020,
        grade_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ]
    
    return queryInterface.bulkInsert('Classes', classes, {});
    
  },

  down: (queryInterface, Sequelize) => {
    
      return queryInterface.bulkDelete('Classes', null, {});
    
  }
};
